name: Update Latest.json

on:
    workflow_run:
        workflows: ["publish"]
        types:
            - completed

jobs:
    update-latest:
        permissions:
            contents: read
        runs-on: ubuntu-22.04
        steps:
            - name: Download signatures
              uses: actions/download-artifact@v3
              with:
                name: signatures
        
            - name: Get version from package.json
              id: get_version
              run: |
                VERSION=$(jq -r .version package.json)
                echo "VERSION=$VERSION" >> $GITHUB_ENV

            - name: Set Environment Variables
              run: |
                echo "VERSION=${{ env.VERSION }}" >> $GITHUB_ENV
                echo "PUB_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV
                echo "NOTES=See the description of the respective release to discover what is new! https://github.com/byChratos/discord-tools/releases" >> $GITHUB_ENV

                echo "SIGN_darwin_x86=$(cat artifacts/discord-tools.app.tar.gz.sig 2>/dev/null || echo 'No Signature')" >> $GITHUB_ENV
                echo "SIGN_darwin_arm=$(cat artifacts/discord-tools.app.tar.gz.sig 2>/dev/null || echo 'No Signature')" >> $GITHUB_ENV
                echo "SIGN_linux=$(cat artifacts/discord-tools_${{ env.VERSION }}_amd64.AppImage.sig 2>/dev/null || echo 'No Signature')" >> $GITHUB_ENV
                echo "SIGN_win=$(cat artifacts/discord-tools_${{ env.VERSION }}_x64-setup.exe.sig 2>/dev/null || echo 'No Signature')" >> $GITHUB_ENV

                echo "URL_darwin_x86=https://github.com/byChratos/reponame/releases/download/discord-tools-${{ env.VERSION }}/discord-tools_x64.app.tar.gz" >> $GITHUB_ENV
                echo "URL_darwin_arm=https://github.com/byChratos/reponame/releases/download/discord-tools-${{ env.VERSION }}/discord-tools_aarch64.app.tar.gz" >> $GITHUB_ENV
                echo "URL_linux=https://github.com/byChratos/reponame/releases/download/discord-tools-${{ env.VERSION }}/discord-tools_${{ env.VERSION }}_amd64.AppImage" >> $GITHUB_ENV
                echo "URL_win=https://github.com/byChratos/reponame/releases/download/discord-tools-${{ env.VERSION }}/discord-tools_${{ env.VERSION }}_x64-setup.exe" >> $GITHUB_ENV

            - name: Update latest.json
              run: |
                GIST_ID="${{ vars.GIST_ID }}"

                CONFIG_CONTENT=$(envsubst < templates/latest.json | jq -c .)
                PAYLOAD=$(jq -n --arg content "$CONFIG_CONTENT" '{files: {latest.json: {content: $content}}}')

                # Gist aktualisieren
                curl -L \
                    -X PATCH \
                    "https://api.github.com/gists/$GIST_ID" \
                    -H "Authorization: Bearer ${{ secrets.GIST_TOKEN }}" \
                    -H "Accept: application/vnd.github+json" \
                    -H "X-GitHub-Api-Version: 2022-11-28" \
                    -d "$PAYLOAD"